use_frameworks!

target 'newpod_Example', :exclusive => true do
  pod 'newpod', :path => '1234../'
end

target 'newpod_Tests', :exclusive => true do
  pod 'newpod', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
